/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Piezas.Luces.LuzCarro;
import Piezas.Luces.LuzIntermitente;
import Piezas.Seguridad.Cinturon;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author llean
 */
public class IFrmBotones extends javax.swing.JInternalFrame {
    private Timer tempDir;
    private IFrmDash dash;
    private LuzIntermitente dirIzq;
    private LuzIntermitente dirDer;
    private LuzCarro luz;
    private Cinturon cintuIzq;
    private Cinturon cintuDer;
    private boolean emergencia;
    /**
     * Creates new form IFrmBotones
     */
    public IFrmBotones(IFrmDash dash) {
        initComponents();
        tglBtnBaja.setSelected(true);
        instanciarAtributos(dash);
        this.tempDir = new Timer(750, (ActionEvent e) -> {
            if(dirIzq.isActiva() && !emergencia) {
                dirIzq.alternarEstado();
                if (dash.getLblIzquierdaOn().isEnabled()) dash.getLblIzquierdaOn().setEnabled(false);
                else dash.getLblIzquierdaOn().setEnabled(true);
            } else if(dirDer.isActiva() && !emergencia) {
                dirDer.alternarEstado();
                if (dash.getLblDerechaOn().isEnabled()) dash.getLblDerechaOn().setEnabled(false);
                else dash.getLblDerechaOn().setEnabled(true);
            } else if (emergencia) {
                dirIzq.alternarEstado();
                if (dash.getLblIzquierdaOn().isEnabled()) dash.getLblIzquierdaOn().setEnabled(false);
                else dash.getLblIzquierdaOn().setEnabled(true);
                dirDer.alternarEstado();
                if (dash.getLblDerechaOn().isEnabled()) dash.getLblDerechaOn().setEnabled(false);
                else dash.getLblDerechaOn().setEnabled(true);
            }
        });
    }
    
    public void instanciarAtributos(IFrmDash dash) {
        this.dash = dash;
        this.dirIzq = new LuzIntermitente();
        this.dirDer = new LuzIntermitente();
        this.luz = new LuzCarro();
        this.cintuIzq = new Cinturon();
        this.cintuDer = new Cinturon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDirIzq = new javax.swing.JButton();
        btnCinIzq = new javax.swing.JButton();
        btnDirDer = new javax.swing.JButton();
        btnCinDer = new javax.swing.JButton();
        btnEmer = new javax.swing.JButton();
        tglBtnAlta = new javax.swing.JToggleButton();
        tglBtnBaja = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        btnDirIzq.setBackground(new java.awt.Color(153, 153, 153));
        btnDirIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/left-arrow.png"))); // NOI18N
        btnDirIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirIzqActionPerformed(evt);
            }
        });

        btnCinIzq.setBackground(new java.awt.Color(153, 153, 153));
        btnCinIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatLeft.png"))); // NOI18N
        btnCinIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinIzqActionPerformed(evt);
            }
        });

        btnDirDer.setBackground(new java.awt.Color(153, 153, 153));
        btnDirDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/right-arrow.png"))); // NOI18N
        btnDirDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirDerActionPerformed(evt);
            }
        });

        btnCinDer.setBackground(new java.awt.Color(153, 153, 153));
        btnCinDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatRight.png"))); // NOI18N
        btnCinDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinDerActionPerformed(evt);
            }
        });

        btnEmer.setBackground(new java.awt.Color(153, 153, 153));
        btnEmer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/emergency.png"))); // NOI18N
        btnEmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmerActionPerformed(evt);
            }
        });

        tglBtnAlta.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car-lights (1).png"))); // NOI18N
        tglBtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnAltaActionPerformed(evt);
            }
        });

        tglBtnBaja.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car-lights.png"))); // NOI18N
        tglBtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnBajaActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(153, 153, 153));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/parking-lights.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDirIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDirDer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tglBtnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglBtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCinIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCinDer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDirIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDirDer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglBtnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCinIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCinDer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCinIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinIzqActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCinIzqActionPerformed

    private void btnDirIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirIzqActionPerformed
        if (!dirIzq.isActiva()) {
            if (dirDer.isActiva()) {
                dirDer.desactivar();
                dash.getLblDerechaOn().setEnabled(false);
            }
            dirIzq.activar();
            dash.getLblIzquierdaOn().setEnabled(true);
            tempDir.stop();
            tempDir.start();
        } else {
            dirIzq.desactivar();
            dash.getLblIzquierdaOn().setEnabled(false);
            tempDir.stop();
        }
    }//GEN-LAST:event_btnDirIzqActionPerformed

    private void btnEmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmerActionPerformed
        if (!emergencia) {
            this.emergencia = true;
            dirDer.desactivar();
            dash.getLblDerechaOn().setEnabled(false);
            dirIzq.desactivar();
            dash.getLblIzquierdaOn().setEnabled(false);
            
            dirIzq.activar();
            dash.getLblIzquierdaOn().setEnabled(true);
            dirDer.activar();
            dash.getLblDerechaOn().setEnabled(true);
            tempDir.stop();
            tempDir.start();
        } else {
            this.emergencia = false;
            dirIzq.desactivar();
            dash.getLblIzquierdaOn().setEnabled(false);
            dirDer.desactivar();
            dash.getLblDerechaOn().setEnabled(false);
            tempDir.stop();
        }
    }//GEN-LAST:event_btnEmerActionPerformed

    private void btnDirDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirDerActionPerformed
        if (!dirDer.isActiva()) {
            if (dirIzq.isActiva()) {
                dirIzq.desactivar();
                dash.getLblIzquierdaOn().setEnabled(false);
            }
            dirDer.activar();
            dash.getLblDerechaOn().setEnabled(true);
            tempDir.stop();
            tempDir.start();
        } else {
            dirDer.desactivar();
            dash.getLblDerechaOn().setEnabled(false);
            tempDir.stop();
        }
    }//GEN-LAST:event_btnDirDerActionPerformed

    private void btnCinDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinDerActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCinDerActionPerformed

    private void tglBtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnAltaActionPerformed
        if (!luz.isIntensidadLuz()) {
            tglBtnBaja.setSelected(false);
            luz.cambiarIntensidad();
            if (luz.isActiva()) {
                dash.getLblLuzBaja().setEnabled(false);
                dash.getLblLuzAlta().setEnabled(true);
            }
        }
    }//GEN-LAST:event_tglBtnAltaActionPerformed

    private void tglBtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnBajaActionPerformed
        if (luz.isIntensidadLuz()) {
            tglBtnAlta.setSelected(false);
            luz.cambiarIntensidad();
            if (luz.isActiva()) {
                dash.getLblLuzAlta().setEnabled(false);
                dash.getLblLuzBaja().setEnabled(true);
            }
        }
    }//GEN-LAST:event_tglBtnBajaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (!luz.isActiva()) {
            luz.activar();
            if (!luz.isIntensidadLuz()) dash.getLblLuzBaja().setEnabled(true);
            else dash.getLblLuzAlta().setEnabled(true);
        } else {
            luz.desactivar();
            if (!luz.isIntensidadLuz()) dash.getLblLuzBaja().setEnabled(false);
            else dash.getLblLuzAlta().setEnabled(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCinDer;
    private javax.swing.JButton btnCinIzq;
    private javax.swing.JButton btnDirDer;
    private javax.swing.JButton btnDirIzq;
    private javax.swing.JButton btnEmer;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton tglBtnAlta;
    private javax.swing.JToggleButton tglBtnBaja;
    // End of variables declaration//GEN-END:variables
}
