/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Piezas.Luces.LuzCarro;
import Piezas.Luces.LuzIntermitente;
import Piezas.Seguridad.Cinturon;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author llean
 */
public class IFrmBotones extends javax.swing.JInternalFrame {
    private Timer tempDir;
    private IFrmDash dash;
    private LuzIntermitente dirIzq;
    private LuzIntermitente dirDer;
    private LuzCarro luz;
    private Cinturon cintuIzq;
    private Cinturon cintuDer;
    private boolean emergencia;
    /**
     * Creates new form IFrmBotones
     */
    public IFrmBotones(IFrmDash dash) {
        initComponents();
        tglBtnBaja.setSelected(true);
        instanciarAtributos(dash);
        this.tempDir = new Timer(750, (ActionEvent e) -> {
            if(dirIzq.isActiva() && !emergencia) {
                dirIzq.alternarEstado();
                if (dash.getLblIzquierdaOn().isEnabled()) dash.getLblIzquierdaOn().setEnabled(false);
                else dash.getLblIzquierdaOn().setEnabled(true);
            } else if(dirDer.isActiva() && !emergencia) {
                dirDer.alternarEstado();
                if (dash.getLblDerechaOn().isEnabled()) dash.getLblDerechaOn().setEnabled(false);
                else dash.getLblDerechaOn().setEnabled(true);
            } else if (emergencia) {
                dirIzq.alternarEstado();
                if (dash.getLblIzquierdaOn().isEnabled()) dash.getLblIzquierdaOn().setEnabled(false);
                else dash.getLblIzquierdaOn().setEnabled(true);
                dirDer.alternarEstado();
                if (dash.getLblDerechaOn().isEnabled()) dash.getLblDerechaOn().setEnabled(false);
                else dash.getLblDerechaOn().setEnabled(true);
            }
        });
    }
    
    public void instanciarAtributos(IFrmDash dash) {
        this.dash = dash;
        this.dirIzq = new LuzIntermitente();
        this.dirDer = new LuzIntermitente();
        this.luz = new LuzCarro();
        this.cintuIzq = new Cinturon();
        this.cintuDer = new Cinturon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglBtnAlta = new javax.swing.JToggleButton();
        tglBtnBaja = new javax.swing.JToggleButton();
        tglBtnLuces = new javax.swing.JToggleButton();
        tglBtnLeftSeat = new javax.swing.JToggleButton();
        tglBtnRightSeat = new javax.swing.JToggleButton();
        tglBtnDirIzq = new javax.swing.JToggleButton();
        tglBtnDirDer = new javax.swing.JToggleButton();
        tglBtnEmer = new javax.swing.JToggleButton();

        tglBtnAlta.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car-lights (1).png"))); // NOI18N
        tglBtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnAltaActionPerformed(evt);
            }
        });

        tglBtnBaja.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car-lights.png"))); // NOI18N
        tglBtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnBajaActionPerformed(evt);
            }
        });

        tglBtnLuces.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnLuces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/parking-lights.png"))); // NOI18N
        tglBtnLuces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLucesActionPerformed(evt);
            }
        });

        tglBtnLeftSeat.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnLeftSeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatLeft.png"))); // NOI18N
        tglBtnLeftSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnLeftSeatActionPerformed(evt);
            }
        });

        tglBtnRightSeat.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnRightSeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatRight.png"))); // NOI18N
        tglBtnRightSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnRightSeatActionPerformed(evt);
            }
        });

        tglBtnDirIzq.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnDirIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/left-arrow.png"))); // NOI18N
        tglBtnDirIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnDirIzqActionPerformed(evt);
            }
        });

        tglBtnDirDer.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnDirDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/right-arrow.png"))); // NOI18N
        tglBtnDirDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnDirDerActionPerformed(evt);
            }
        });

        tglBtnEmer.setBackground(new java.awt.Color(153, 153, 153));
        tglBtnEmer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/emergency.png"))); // NOI18N
        tglBtnEmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnEmerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tglBtnLuces, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(tglBtnDirIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tglBtnDirDer, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(tglBtnEmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tglBtnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(tglBtnLeftSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tglBtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tglBtnRightSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglBtnDirIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBtnDirDer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglBtnLuces, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBtnEmer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglBtnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglBtnRightSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBtnLeftSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglBtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnAltaActionPerformed
        if (!luz.isIntensidadLuz()) {
            tglBtnBaja.setSelected(false);
            luz.cambiarIntensidad();
            if (luz.isActiva()) {
                dash.getLblLuzBaja().setEnabled(false);
                dash.getLblLuzAlta().setEnabled(true);
            }
        }
    }//GEN-LAST:event_tglBtnAltaActionPerformed

    private void tglBtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnBajaActionPerformed
        if (luz.isIntensidadLuz()) {
            tglBtnAlta.setSelected(false);
            luz.cambiarIntensidad();
            if (luz.isActiva()) {
                dash.getLblLuzAlta().setEnabled(false);
                dash.getLblLuzBaja().setEnabled(true);
            }
        }
    }//GEN-LAST:event_tglBtnBajaActionPerformed

    private void tglBtnLucesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLucesActionPerformed
        if (!luz.isActiva()) {
            luz.activar();
            if (!luz.isIntensidadLuz()) dash.getLblLuzBaja().setEnabled(true);
            else dash.getLblLuzAlta().setEnabled(true);
        } else {
            luz.desactivar();
            if (!luz.isIntensidadLuz()) dash.getLblLuzBaja().setEnabled(false);
            else dash.getLblLuzAlta().setEnabled(false);
        }
    }//GEN-LAST:event_tglBtnLucesActionPerformed

    private void tglBtnLeftSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnLeftSeatActionPerformed
       if (!cintuIzq.isPuesto()) {
           cintuIzq.poner();
           dash.getLblSeatbeltD().setEnabled(true);
       } else {
           cintuIzq.quitar();
           dash.getLblSeatbeltD().setEnabled(false);
       }
    }//GEN-LAST:event_tglBtnLeftSeatActionPerformed

    private void tglBtnRightSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnRightSeatActionPerformed
        if (!cintuDer.isPuesto()) {
           cintuDer.poner();
           dash.getLblSeatbeltP().setEnabled(true);
       } else {
           cintuDer.quitar();
           dash.getLblSeatbeltP().setEnabled(false);
       }
    }//GEN-LAST:event_tglBtnRightSeatActionPerformed

    public void desactivarDirIzq() {
        dirIzq.desactivar();
        dash.getLblIzquierdaOn().setEnabled(false);
    }
    
    public void desactivarDirDer() {
        dirDer.desactivar();
        dash.getLblDerechaOn().setEnabled(false);
    }
    
    public void activarDirIzq() {
        dirIzq.activar();
        dash.getLblIzquierdaOn().setEnabled(true);
    }
    
    public void activarDirDer() {
        dirDer.activar();
        dash.getLblDerechaOn().setEnabled(true);
    }
    
    private void tglBtnDirIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnDirIzqActionPerformed
        if (!dirIzq.isActiva() && !emergencia) {
            tempDir.stop();
            if (dirDer.isActiva()) {
                desactivarDirDer();
                tglBtnDirDer.setSelected(false);
            }
            activarDirIzq();
            tempDir.start();
        } else if (emergencia) {
            desactivarDirDer();
            this.emergencia = false;
            tglBtnEmer.setSelected(false);
        } else {
            desactivarDirIzq();
            tempDir.stop();
        }
    }//GEN-LAST:event_tglBtnDirIzqActionPerformed

    private void tglBtnDirDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnDirDerActionPerformed
        if (!dirDer.isActiva() && !emergencia) {
            tempDir.stop();
            if (dirIzq.isActiva()) {
                desactivarDirIzq();
                tglBtnDirIzq.setSelected(false);
            } 
            activarDirDer();
            tempDir.start();
        } else if (emergencia) {
            desactivarDirIzq();
            this.emergencia = false;
            tglBtnEmer.setSelected(false);
        } else {
            desactivarDirDer();
            tempDir.stop();
        }
    }//GEN-LAST:event_tglBtnDirDerActionPerformed

    private void tglBtnEmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnEmerActionPerformed
        if (!emergencia) {
            this.emergencia = true;
            desactivarDirDer();
            tglBtnDirDer.setSelected(false);
            desactivarDirIzq();
            tglBtnDirIzq.setSelected(false);
            
            activarDirIzq();
            activarDirDer();
            tempDir.stop();
            tempDir.start();
        } else {
            this.emergencia = false;
            desactivarDirIzq();
            desactivarDirDer();
            tempDir.stop();
        }
    }//GEN-LAST:event_tglBtnEmerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton tglBtnAlta;
    private javax.swing.JToggleButton tglBtnBaja;
    private javax.swing.JToggleButton tglBtnDirDer;
    private javax.swing.JToggleButton tglBtnDirIzq;
    private javax.swing.JToggleButton tglBtnEmer;
    private javax.swing.JToggleButton tglBtnLeftSeat;
    private javax.swing.JToggleButton tglBtnLuces;
    private javax.swing.JToggleButton tglBtnRightSeat;
    // End of variables declaration//GEN-END:variables
}
