/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import Piezas.Sensores.SensorReversa;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
/**
 *
 * @author llean
 */
public class IFrmCamaraReversa extends javax.swing.JInternalFrame {
SensorReversa reversa;
private int segundo = 3;
    /**
     * Creates new form IFrmCamaraReversa
     */
    public IFrmCamaraReversa() {
        initComponents();
        reversa = new SensorReversa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCamara = new javax.swing.JLabel();
        lblStop = new javax.swing.JLabel();
        btnReversa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(480, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCamara.setBackground(new java.awt.Color(255, 255, 255));
        lblCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/yotota.png"))); // NOI18N
        lblCamara.setOpaque(true);
        getContentPane().add(lblCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 22, -1, -1));

        lblStop.setBackground(new java.awt.Color(153, 0, 0));
        lblStop.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblStop.setForeground(new java.awt.Color(255, 255, 255));
        lblStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStop.setText("Stop!");
        lblStop.setEnabled(false);
        lblStop.setOpaque(true);
        getContentPane().add(lblStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 110, 50));

        btnReversa.setBackground(new java.awt.Color(153, 153, 153));
        btnReversa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReversa.setForeground(new java.awt.Color(0, 0, 0));
        btnReversa.setText("Reversa");
        btnReversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReversaActionPerformed(evt);
            }
        });
        getContentPane().add(btnReversa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 110, 48));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
            Timer timer = new Timer (1000, new ActionListener (){
            public void actionPerformed(ActionEvent e){
            contador();
            
            }
            });
    
         private void contador() {
             segundo--;
             if(segundo == 0){
                reversa.hayPersona();
                 if (reversa.isPersonaDetectada()) {
                ImageIcon icono2 = new ImageIcon(getClass().getResource("/Iconos/camaraReversaObstruida.png"));
                lblCamara.setIcon(icono2);
                lblStop.setEnabled(true);
                lblStop.setBackground(Color.red);
                timer.stop();
            }
             }
        }
    
    private void btnReversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReversaActionPerformed
        if(!reversa.isActivo()){
            ImageIcon icono = new ImageIcon(getClass().getResource("/Iconos/camaraReversaLibre.png"));
            lblCamara.setIcon(icono);
            reversa.iniciarSensor();
            
            timer.start();
            
       
            
        } else {
             ImageIcon icono = new ImageIcon(getClass().getResource("/Iconos/yotota.png"));
            lblCamara.setIcon(icono);
            reversa.detenerSensor();
            reversa.noHayPersona();
            lblStop.setEnabled(false);
             Color color = new Color(76, 0, 0);
             lblStop.setBackground(color);
             segundo = 3;
        }
        
           
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReversaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReversa;
    private javax.swing.JLabel lblCamara;
    private javax.swing.JLabel lblStop;
    // End of variables declaration//GEN-END:variables
}
