/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Piezas.Climatizacion.Climatizacion;
import Piezas.Radio.Radio;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;

/**
 *
 * @author rodol
 */
public class IFrmRadioClimatizacion extends javax.swing.JInternalFrame {
    private Radio radio;
    private Climatizacion climatizacion;

    /**
     * Creates new form Radio
     */
    public IFrmRadioClimatizacion() {
        initComponents();
        radio = new Radio();
        climatizacion = new Climatizacion();
        inicializar();
        
    }
    
    private void inicializar(){
        btnBluetooth.setEnabled(radio.isEncendida());
        btnAMOn.setEnabled(radio.isEncendida());
        btnFMOn.setEnabled(radio.isEncendida());
        txtRadio.setText(radio.getNombreEstaciones());
        jslCiclar.setValue(radio.getIndiceEstaciones());
        jslCiclar.setEnabled(false);
        jslCiclar.setValueIsAdjusting(false);
        
        
        jspVelocidad.setValue(climatizacion.getIndiceVelocidad());
        txtVelocidad.setText(climatizacion.getNombreVelocidades());  
        JComponent editor = jspVelocidad.getEditor();
        JFormattedTextField spinner = ((JSpinner.DefaultEditor) editor).getTextField();
        spinner.setEditable(false);
        
        jspTemperatura.setEnabled(false);
        jspTemperatura.setValue(24);
        lblIconoTemperatura.setEnabled(climatizacion.isEncendido());
        lblTemperaturaTitulo.setEnabled(climatizacion.isEncendido());
        lblTemperatura.setText(climatizacion.getModoTemperatura());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoEstacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jslCiclar = new javax.swing.JSlider();
        txtVelocidad = new javax.swing.JTextField();
        btnAMOn = new javax.swing.JButton();
        btnFMOn = new javax.swing.JButton();
        jspVelocidad = new javax.swing.JSpinner();
        jspTemperatura = new javax.swing.JSpinner();
        lblTemperaturaTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        lblIconoTemperatura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCircles = new javax.swing.JLabel();
        btnEstadoRadio = new javax.swing.JButton();
        lblTemperatura = new javax.swing.JLabel();
        btnBluetooth = new javax.swing.JToggleButton();
        lblEstadoBluetooth = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(480, 360));
        setPreferredSize(new java.awt.Dimension(432, 360));

        lblTipoEstacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/off.png"))); // NOI18N
        lblTipoEstacion.setPreferredSize(new java.awt.Dimension(38, 39));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jslCiclar.setMajorTickSpacing(1);
        jslCiclar.setMaximum(4);
        jslCiclar.setMinorTickSpacing(1);
        jslCiclar.setPaintLabels(true);
        jslCiclar.setPaintTicks(true);
        jslCiclar.setSnapToTicks(true);
        jslCiclar.setToolTipText("");
        jslCiclar.setValue(0);
        jslCiclar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jslCiclar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslCiclarStateChanged(evt);
            }
        });

        txtVelocidad.setEditable(false);
        txtVelocidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtVelocidad.setForeground(new java.awt.Color(0, 0, 0));
        txtVelocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAMOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/am(1).png"))); // NOI18N
        btnAMOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMOnActionPerformed(evt);
            }
        });

        btnFMOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fm(1).png"))); // NOI18N
        btnFMOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFMOnActionPerformed(evt);
            }
        });

        jspVelocidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        jspVelocidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jspVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspVelocidadStateChanged(evt);
            }
        });

        jspTemperatura.setModel(new javax.swing.SpinnerNumberModel(24, 18, 35, 1));
        jspTemperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspTemperaturaStateChanged(evt);
            }
        });

        lblTemperaturaTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTemperaturaTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTemperaturaTitulo.setText("Temperatura");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Velocidad");

        txtRadio.setEditable(false);
        txtRadio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtRadio.setForeground(new java.awt.Color(0, 0, 0));
        txtRadio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblIconoTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/thermometer.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/speedometer.png"))); // NOI18N

        lblCircles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/circleWhite.png"))); // NOI18N

        btnEstadoRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/botonEncendido.png"))); // NOI18N
        btnEstadoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoRadioActionPerformed(evt);
            }
        });

        lblTemperatura.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnBluetooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bluetooth.png"))); // NOI18N
        btnBluetooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBluetoothActionPerformed(evt);
            }
        });

        lblEstadoBluetooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/switch-off.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTipoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jslCiclar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(111, 111, 111)
                .addComponent(lblTemperaturaTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jspVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lblIconoTemperatura)
                .addGap(8, 8, 8)
                .addComponent(jspTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCircles)
                .addGap(26, 26, 26)
                .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBluetooth, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstadoBluetooth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnFMOn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnAMOn))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnEstadoRadio))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnFMOn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnAMOn))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnEstadoRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jslCiclar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTipoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstadoBluetooth)
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnBluetooth)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTemperaturaTitulo)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblIconoTemperatura)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCircles)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFMOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFMOnActionPerformed
        ImageIcon iconoFM = new ImageIcon(getClass().getResource("/Iconos/fm(1).png"));
        if (!radio.isBluetoothActivo()) {
            lblTipoEstacion.setIcon(iconoFM);
            jslCiclar.setEnabled(true);
             jslCiclar.setValue(1);
        }
    }//GEN-LAST:event_btnFMOnActionPerformed

    private void btnAMOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMOnActionPerformed
          ImageIcon iconoAM = new ImageIcon(getClass().getResource("/Iconos/am(1).png"));
        if (!radio.isBluetoothActivo()) {
            lblTipoEstacion.setIcon(iconoAM);
            jslCiclar.setEnabled(true);
            jslCiclar.setValue(1);
        }
    }//GEN-LAST:event_btnAMOnActionPerformed

    private void btnBluetoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBluetoothActionPerformed
        ImageIcon iconoBluetoothOn = new ImageIcon(getClass().getResource("/Iconos/bluetooth.png"));
        ImageIcon iconoBluetoothOff = new ImageIcon(getClass().getResource("/Iconos/deactivate.png"));
        ImageIcon iconoOfff = new ImageIcon(getClass().getResource("/Iconos/switch-off.png"));
        ImageIcon iconoOn = new ImageIcon(getClass().getResource("/Iconos/switch-on.png"));
        ImageIcon iconoOff = new ImageIcon(getClass().getResource("/Iconos/off.png"));
        if (!radio.isBluetoothActivo()){
            radio.activarBluetooth();
            btnBluetooth.setIcon(iconoBluetoothOff);
            lblTipoEstacion.setIcon(iconoOff);
            jslCiclar.setValue(0);
            radio.cambiar(jslCiclar.getValue());
            txtRadio.setText(radio.getNombreEstaciones());
            jslCiclar.setEnabled(false);
            lblEstadoBluetooth.setIcon(iconoOn);
        }else{
            radio.desactivarBluetooth();
            btnBluetooth.setIcon(iconoBluetoothOn);
            lblEstadoBluetooth.setIcon(iconoOfff);
        }
    }//GEN-LAST:event_btnBluetoothActionPerformed

    private void btnEstadoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoRadioActionPerformed
        ImageIcon iconoOff = new ImageIcon(getClass().getResource("/Iconos/off.png"));
        ImageIcon iconoBluetoothOn = new ImageIcon(getClass().getResource("/Iconos/bluetooth.png"));
        ImageIcon iconoOfff = new ImageIcon(getClass().getResource("/Iconos/switch-off.png"));
        if(!radio.isEncendida()){
            radio.encender();
            btnBluetooth.setEnabled(radio.isEncendida());
            btnAMOn.setEnabled(radio.isEncendida());
            btnFMOn.setEnabled(radio.isEncendida());
        } else {
            radio.apagar();
            lblTipoEstacion.setIcon(iconoOff);
            radio.desactivarBluetooth();
            btnBluetooth.setIcon(iconoBluetoothOn);
            btnBluetooth.setSelected(false);
            btnBluetooth.setEnabled(radio.isEncendida());
            lblEstadoBluetooth.setIcon(iconoOfff);
            btnAMOn.setEnabled(radio.isEncendida());
            btnFMOn.setEnabled(radio.isEncendida());
            txtRadio.setText(radio.getNombreEstaciones());
            jslCiclar.setValue(radio.getIndiceEstaciones());
            jslCiclar.setEnabled(false);
        }
    }//GEN-LAST:event_btnEstadoRadioActionPerformed

    private void jslCiclarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslCiclarStateChanged
        if (radio.isEncendida() && !radio.isBluetoothActivo()){
            int estaciones = jslCiclar.getValue();
            System.out.println("estaciones " + estaciones);
            radio.cambiar(estaciones);
            txtRadio.setText(radio.getNombreEstaciones());
        } 
        
        if (radio.getIndiceEstaciones() == 0){
            ImageIcon iconoOff = new ImageIcon(getClass().getResource("/Iconos/off.png"));
            lblTipoEstacion.setIcon(iconoOff);
            jslCiclar.setEnabled(false);
        }
    }//GEN-LAST:event_jslCiclarStateChanged

    private void jspVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspVelocidadStateChanged
        int indiceVelocidad = Integer.parseInt(jspVelocidad.getValue().toString());
        int indiceTemperatura = Integer.parseInt(jspTemperatura.getValue().toString());
        if (indiceVelocidad > 0){
            climatizacion.encender();
            jspTemperatura.setEnabled(climatizacion.isEncendido());
            lblIconoTemperatura.setEnabled(climatizacion.isEncendido());
            lblTemperaturaTitulo.setEnabled(climatizacion.isEncendido());
            climatizacion.setLimiteTemperatura(indiceTemperatura);
            lblTemperatura.setText(climatizacion.getModoTemperatura());
        }else if (indiceVelocidad == 0){
            climatizacion.apagar();
            jspTemperatura.setValue(24);
            jspTemperatura.setEnabled(false);
            climatizacion.setLimiteTemperatura(24);
            lblTemperatura.setText(climatizacion.getModoTemperatura());
            txtVelocidad.setText(climatizacion.getNombreVelocidades());
        }
      
        if (climatizacion.isEncendido()){
            climatizacion.cambiar(indiceVelocidad);
            txtVelocidad.setText(climatizacion.getNombreVelocidades());
        }
        
    }//GEN-LAST:event_jspVelocidadStateChanged

    private void jspTemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspTemperaturaStateChanged
        if (climatizacion.isEncendido()){
            jspTemperatura.setEnabled(true);
        }else{
            jspTemperatura.setEnabled(true);
        }
        int indice = Integer.parseInt(jspTemperatura.getValue().toString());
        climatizacion.setLimiteTemperatura(indice);
        lblTemperatura.setText(climatizacion.getModoTemperatura());
        
        if (climatizacion.getLimiteTemperatura() >= 18 && climatizacion.getLimiteTemperatura() <= 22){
            ImageIcon iconoCircleBlue = new ImageIcon(getClass().getResource("/Iconos/circleBlue.png"));
            lblCircles.setIcon(iconoCircleBlue);
        }else if (climatizacion.getLimiteTemperatura() >= 23 && climatizacion.getLimiteTemperatura() <= 29){
            ImageIcon iconoCircleWhite = new ImageIcon(getClass().getResource("/Iconos/circleWhite.png"));
            lblCircles.setIcon(iconoCircleWhite); 
        }else if (climatizacion.getLimiteTemperatura() >= 30 && climatizacion.getLimiteTemperatura() <= 35) {
                ImageIcon iconoCircleRed = new ImageIcon(getClass().getResource("/Iconos/circleRed.png"));
            lblCircles.setIcon(iconoCircleRed);
        }
        
    }//GEN-LAST:event_jspTemperaturaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAMOn;
    private javax.swing.JToggleButton btnBluetooth;
    private javax.swing.JButton btnEstadoRadio;
    private javax.swing.JButton btnFMOn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jslCiclar;
    private javax.swing.JSpinner jspTemperatura;
    private javax.swing.JSpinner jspVelocidad;
    private javax.swing.JLabel lblCircles;
    private javax.swing.JLabel lblEstadoBluetooth;
    private javax.swing.JLabel lblIconoTemperatura;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperaturaTitulo;
    private javax.swing.JLabel lblTipoEstacion;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
