/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;


import javax.swing.JLabel;


/**
 *
 * @author rodol
 */
public class IFrmLimpiaParabrisas extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form IFrmLimpiaParabrisas
     */
    public IFrmLimpiaParabrisas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblParabrisas = new javax.swing.JLabel();
        lblLimpiaParabrisas = new javax.swing.JLabel();
        lblLimpiaParabrisas1 = new javax.swing.JLabel();

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1182, 436));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1182, 436));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1182, 436));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblParabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Parabrisas2.png"))); // NOI18N
        jLayeredPane1.add(lblParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 460));

        lblLimpiaParabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/LimpiaParabrisas.png"))); // NOI18N
        jLayeredPane1.setLayer(lblLimpiaParabrisas, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(lblLimpiaParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -10, 490, 610));

        lblLimpiaParabrisas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/LimpiaParabrisas.png"))); // NOI18N
        jLayeredPane1.setLayer(lblLimpiaParabrisas1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(lblLimpiaParabrisas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, 490, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getlblLimpiaParabrisas() {
        return lblLimpiaParabrisas;
    }

    public JLabel getlblLimpiaParabrisas1() {
        return lblLimpiaParabrisas1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblLimpiaParabrisas;
    private javax.swing.JLabel lblLimpiaParabrisas1;
    private javax.swing.JLabel lblParabrisas;
    // End of variables declaration//GEN-END:variables
}
