/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Piezas.Climatizacion.Climatizacion;
import Piezas.Radio.Radio;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;

/**
 *
 * @author rodol
 */
public class IFrmRadioClimatizacion extends javax.swing.JInternalFrame {

    private Radio radio;
    private Climatizacion climatizacion;
    private ImageIcon iconoCircleBlue;
    private ImageIcon iconoCircleRed;

    /**
     * Creates new form Radio
     */
    public IFrmRadioClimatizacion() {
        initComponents();
        radio = new Radio();
        climatizacion = new Climatizacion();
        iconoCircleBlue = new ImageIcon(getClass().getResource("/Iconos/circleBlue.png"));
        iconoCircleRed = new ImageIcon(getClass().getResource("/Iconos/circleRed.png"));
        inicializar();
    }

    private void inicializar() {
        btnBluetooth.setEnabled(radio.isEncendida());
        btnAMOn.setEnabled(radio.isEncendida());
        btnFMOn.setEnabled(radio.isEncendida());
        txtRadio.setText(radio.getNombreEstaciones());
        jslCiclar.setValue(radio.getIndiceEstaciones());
        jslCiclar.setEnabled(radio.isEncendida());

        jspVelocidad.setValue(climatizacion.getIndiceVelocidad());
        txtVelocidad.setText(climatizacion.getNombreVelocidades());
        JComponent editor = jspVelocidad.getEditor();
        JFormattedTextField spinner = ((JSpinner.DefaultEditor) editor).getTextField();
        spinner.setEditable(false);

        jspTemperatura.setEnabled(climatizacion.isEncendido());
        lblIconoTemperatura.setEnabled(climatizacion.isEncendido());
        lblTemperaturaTitulo.setEnabled(climatizacion.isEncendido());
        lblTipoTemperatura.setVisible(climatizacion.isEncendido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoEstacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jslCiclar = new javax.swing.JSlider();
        txtVelocidad = new javax.swing.JTextField();
        btnAMOn = new javax.swing.JButton();
        btnFMOn = new javax.swing.JButton();
        jspVelocidad = new javax.swing.JSpinner();
        jspTemperatura = new javax.swing.JSpinner();
        lblTemperaturaTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        lblIconoTemperatura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCircles = new javax.swing.JLabel();
        btnEstadoRadio = new javax.swing.JButton();
        btnBluetooth = new javax.swing.JToggleButton();
        lblEstadoBluetooth = new javax.swing.JLabel();
        lblTipoTemperatura = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(480, 360));
        setPreferredSize(new java.awt.Dimension(432, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipoEstacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/off.png"))); // NOI18N
        lblTipoEstacion.setPreferredSize(new java.awt.Dimension(38, 39));
        getContentPane().add(lblTipoEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 108, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 10, 130));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 420, 10));

        jslCiclar.setMajorTickSpacing(1);
        jslCiclar.setMaximum(4);
        jslCiclar.setMinimum(1);
        jslCiclar.setMinorTickSpacing(1);
        jslCiclar.setPaintLabels(true);
        jslCiclar.setPaintTicks(true);
        jslCiclar.setSnapToTicks(true);
        jslCiclar.setToolTipText("");
        jslCiclar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jslCiclar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslCiclarStateChanged(evt);
            }
        });
        getContentPane().add(jslCiclar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        txtVelocidad.setEditable(false);
        txtVelocidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtVelocidad.setForeground(new java.awt.Color(0, 0, 0));
        txtVelocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 270, -1));

        btnAMOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/am(1).png"))); // NOI18N
        btnAMOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMOnActionPerformed(evt);
            }
        });
        getContentPane().add(btnAMOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btnFMOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fm(1).png"))); // NOI18N
        btnFMOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFMOnActionPerformed(evt);
            }
        });
        getContentPane().add(btnFMOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jspVelocidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        jspVelocidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jspVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspVelocidadStateChanged(evt);
            }
        });
        getContentPane().add(jspVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jspTemperatura.setModel(new javax.swing.SpinnerNumberModel(18, 18, 23, 1));
        jspTemperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspTemperaturaStateChanged(evt);
            }
        });
        getContentPane().add(jspTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        lblTemperaturaTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTemperaturaTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTemperaturaTitulo.setText("Temperatura");
        getContentPane().add(lblTemperaturaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Velocidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtRadio.setEditable(false);
        txtRadio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtRadio.setForeground(new java.awt.Color(0, 0, 0));
        txtRadio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 270, -1));

        lblIconoTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/thermometer.png"))); // NOI18N
        getContentPane().add(lblIconoTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/speedometer.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblCircles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AC_mitad.png"))); // NOI18N
        getContentPane().add(lblCircles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnEstadoRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/botonEncendido.png"))); // NOI18N
        btnEstadoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoRadioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        btnBluetooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bluetooth.png"))); // NOI18N
        btnBluetooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBluetoothActionPerformed(evt);
            }
        });
        getContentPane().add(btnBluetooth, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 44, -1));

        lblEstadoBluetooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/switch-off.png"))); // NOI18N
        getContentPane().add(lblEstadoBluetooth, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 84, -1, -1));

        lblTipoTemperatura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipoTemperatura.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTipoTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFMOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFMOnActionPerformed
        ImageIcon iconoFM = new ImageIcon(getClass().getResource("/Iconos/fm(1).png"));
        if (!radio.isBluetoothActivo()) {
            lblTipoEstacion.setIcon(iconoFM);
            jslCiclar.setEnabled(true);
            jslCiclar.setValue(1);
        }
    }//GEN-LAST:event_btnFMOnActionPerformed

    private void btnAMOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMOnActionPerformed
        ImageIcon iconoAM = new ImageIcon(getClass().getResource("/Iconos/am(1).png"));
        if (!radio.isBluetoothActivo()) {
            lblTipoEstacion.setIcon(iconoAM);
            jslCiclar.setEnabled(true);
            jslCiclar.setValue(1);
        }
    }//GEN-LAST:event_btnAMOnActionPerformed

    private void btnBluetoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBluetoothActionPerformed
        ImageIcon labelOff = new ImageIcon(getClass().getResource("/Iconos/switch-off.png"));
        ImageIcon labelOn = new ImageIcon(getClass().getResource("/Iconos/switch-on.png"));

        if (!radio.isBluetoothActivo()) {
            radio.activarBluetooth();
            jslCiclar.setEnabled(!radio.isBluetoothActivo());
            lblEstadoBluetooth.setIcon(labelOn);
        } else {
            radio.desactivarBluetooth();
            lblEstadoBluetooth.setIcon(labelOff);
            jslCiclar.setEnabled(!radio.isBluetoothActivo());

        }
    }//GEN-LAST:event_btnBluetoothActionPerformed

    private void btnEstadoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoRadioActionPerformed
        ImageIcon iconoOff = new ImageIcon(getClass().getResource("/Iconos/off.png"));
        ImageIcon iconoBluetoothOn = new ImageIcon(getClass().getResource("/Iconos/bluetooth.png"));
        ImageIcon labelOff = new ImageIcon(getClass().getResource("/Iconos/switch-off.png"));
        ImageIcon iconoFM = new ImageIcon(getClass().getResource("/Iconos/fm(1).png"));

        if (!radio.isEncendida()) {
            radio.encender();
            lblTipoEstacion.setIcon(iconoFM);
            actualizarEstadoRadio();
            ciclarSpinner();
        } else {
            radio.apagar();
            lblTipoEstacion.setIcon(iconoOff);
            radio.desactivarBluetooth();
            btnBluetooth.setIcon(iconoBluetoothOn);
            btnBluetooth.setSelected(radio.isEncendida());
            lblEstadoBluetooth.setIcon(labelOff);
            actualizarEstadoRadio();
            jslCiclar.setEnabled(radio.isEncendida());
        }
    }//GEN-LAST:event_btnEstadoRadioActionPerformed

    private void jslCiclarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslCiclarStateChanged
        ciclarSpinner();
    }//GEN-LAST:event_jslCiclarStateChanged

    private void jspVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspVelocidadStateChanged
        ImageIcon iconoHalfCircle = new ImageIcon(getClass().getResource("/Iconos/AC_mitad.png"));
        int indiceVelocidad = Integer.parseInt(jspVelocidad.getValue().toString());
        int indiceTemperatura = Integer.parseInt(jspTemperatura.getValue().toString());

        if (indiceVelocidad > 0) {
            climatizacion.encender();
            jspTemperatura.setEnabled(climatizacion.isEncendido());
            lblIconoTemperatura.setEnabled(climatizacion.isEncendido());
            lblTemperaturaTitulo.setEnabled(climatizacion.isEncendido());
            climatizacion.setLimiteTemperatura(indiceTemperatura);
            lblTipoTemperatura.setVisible(climatizacion.isEncendido());
            lblTipoTemperatura.setText(climatizacion.getModoTemperatura());
            lblCircles.setIcon(iconoCircleBlue);
        } else if (indiceVelocidad == 0) {
            climatizacion.apagar();
            jspTemperatura.setValue(18);
            jspTemperatura.setEnabled(climatizacion.isEncendido());
            lblTipoTemperatura.setVisible(climatizacion.isEncendido());
            txtVelocidad.setText(climatizacion.getNombreVelocidades());
            lblCircles.setIcon(iconoHalfCircle);
        }

        if (climatizacion.isEncendido()) {
            climatizacion.cambiar(indiceVelocidad);
            txtVelocidad.setText(climatizacion.getNombreVelocidades());
        }
    }//GEN-LAST:event_jspVelocidadStateChanged

    private void jspTemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspTemperaturaStateChanged
        if (climatizacion.isEncendido()) {
            jspTemperatura.setEnabled(climatizacion.isEncendido());
        } else {
            jspTemperatura.setEnabled(climatizacion.isEncendido());
        }

        int indice = Integer.parseInt(jspTemperatura.getValue().toString());
        climatizacion.setLimiteTemperatura(indice);

        if (climatizacion.getLimiteTemperatura() >= 18 && climatizacion.getLimiteTemperatura() <= 20) {
            lblCircles.setIcon(iconoCircleBlue);
            lblTipoTemperatura.setText(climatizacion.getModoTemperatura());
        } else {
            lblCircles.setIcon(iconoCircleRed);
            lblTipoTemperatura.setText(climatizacion.getModoTemperatura());

        }

    }//GEN-LAST:event_jspTemperaturaStateChanged

    private void ciclarSpinner() {
        if (radio.isEncendida()) {
            int estaciones = jslCiclar.getValue();
            radio.cambiar(estaciones);
            txtRadio.setText(radio.getNombreEstaciones());
        }
    }

    private void actualizarEstadoRadio() {
        boolean radioEncendida = radio.isEncendida();
        btnBluetooth.setEnabled(radioEncendida);
        btnAMOn.setEnabled(radioEncendida);
        btnFMOn.setEnabled(radioEncendida);
        jslCiclar.setEnabled(radioEncendida);

        if (!radioEncendida) {
            jslCiclar.setValue(1);
            txtRadio.setText(radio.getNombreEstaciones());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAMOn;
    private javax.swing.JToggleButton btnBluetooth;
    private javax.swing.JButton btnEstadoRadio;
    private javax.swing.JButton btnFMOn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jslCiclar;
    private javax.swing.JSpinner jspTemperatura;
    private javax.swing.JSpinner jspVelocidad;
    private javax.swing.JLabel lblCircles;
    private javax.swing.JLabel lblEstadoBluetooth;
    private javax.swing.JLabel lblIconoTemperatura;
    private javax.swing.JLabel lblTemperaturaTitulo;
    private javax.swing.JLabel lblTipoEstacion;
    private javax.swing.JLabel lblTipoTemperatura;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
