/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author llean
 */
public class IFrmPuertas extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmPuertas
     */
    public IFrmPuertas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlarmaOn = new javax.swing.JLabel();
        lblAlarmaOff = new javax.swing.JLabel();
        lblLuzOn = new javax.swing.JLabel();
        lblLuzOff = new javax.swing.JLabel();
        lblPuertas = new javax.swing.JLabel();
        btnLuzToggle = new javax.swing.JButton();
        btnBloquear = new javax.swing.JToggleButton();
        btnAlarma = new javax.swing.JButton();
        btnCarroOn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(384, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlarmaOn.setBackground(new java.awt.Color(255, 0, 0));
        lblAlarmaOn.setOpaque(true);
        getContentPane().add(lblAlarmaOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, 50));

        lblAlarmaOff.setBackground(new java.awt.Color(153, 0, 0));
        lblAlarmaOff.setOpaque(true);
        getContentPane().add(lblAlarmaOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, 50));

        lblLuzOn.setBackground(new java.awt.Color(255, 255, 255));
        lblLuzOn.setOpaque(true);
        getContentPane().add(lblLuzOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 50));

        lblLuzOff.setBackground(new java.awt.Color(204, 204, 204));
        lblLuzOff.setOpaque(true);
        getContentPane().add(lblLuzOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 50));

        lblPuertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/carClosedDoors.png"))); // NOI18N
        getContentPane().add(lblPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 200));

        btnLuzToggle.setBackground(new java.awt.Color(153, 153, 153));
        btnLuzToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/luzTecho.png"))); // NOI18N
        getContentPane().add(btnLuzToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 50));

        btnBloquear.setBackground(new java.awt.Color(153, 153, 153));
        btnBloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/candadoCerrado.png"))); // NOI18N
        getContentPane().add(btnBloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 80, 50));

        btnAlarma.setBackground(new java.awt.Color(153, 153, 153));
        btnAlarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/alarma.png"))); // NOI18N
        getContentPane().add(btnAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, 50));

        btnCarroOn.setBackground(new java.awt.Color(153, 153, 153));
        btnCarroOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/botonEncendido.png"))); // NOI18N
        btnCarroOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroOnActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarroOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarroOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarroOnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlarma;
    private javax.swing.JToggleButton btnBloquear;
    private javax.swing.JButton btnCarroOn;
    private javax.swing.JButton btnLuzToggle;
    private javax.swing.JLabel lblAlarmaOff;
    private javax.swing.JLabel lblAlarmaOn;
    private javax.swing.JLabel lblLuzOff;
    private javax.swing.JLabel lblLuzOn;
    private javax.swing.JLabel lblPuertas;
    // End of variables declaration//GEN-END:variables
}
