/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author llean
 */
public class IFrmBotones extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmBotones
     */
    public IFrmBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDirIzq = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnCinIzq = new javax.swing.JButton();
        btnDirDer = new javax.swing.JButton();
        btnCinDer = new javax.swing.JButton();
        btnEmer = new javax.swing.JButton();
        btnLuz = new javax.swing.JButton();

        btnDirIzq.setBackground(new java.awt.Color(153, 153, 153));
        btnDirIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/left-arrow.png"))); // NOI18N
        btnDirIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirIzqActionPerformed(evt);
            }
        });

        btnAlta.setBackground(new java.awt.Color(153, 153, 153));
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car-lights (1).png"))); // NOI18N
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setBackground(new java.awt.Color(153, 153, 153));
        btnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car-lights.png"))); // NOI18N
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnCinIzq.setBackground(new java.awt.Color(153, 153, 153));
        btnCinIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatLeft.png"))); // NOI18N
        btnCinIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinIzqActionPerformed(evt);
            }
        });

        btnDirDer.setBackground(new java.awt.Color(153, 153, 153));
        btnDirDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/right-arrow.png"))); // NOI18N
        btnDirDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirDerActionPerformed(evt);
            }
        });

        btnCinDer.setBackground(new java.awt.Color(153, 153, 153));
        btnCinDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatRight.png"))); // NOI18N
        btnCinDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinDerActionPerformed(evt);
            }
        });

        btnEmer.setBackground(new java.awt.Color(153, 153, 153));
        btnEmer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/emergency.png"))); // NOI18N
        btnEmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmerActionPerformed(evt);
            }
        });

        btnLuz.setBackground(new java.awt.Color(153, 153, 153));
        btnLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/light.png"))); // NOI18N
        btnLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnCinIzq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDirIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCinDer, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDirDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEmer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDirIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDirDer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnCinIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCinDer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCinIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinIzqActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCinIzqActionPerformed

    private void btnDirIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirIzqActionPerformed
if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDirIzqActionPerformed

    private void btnEmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmerActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmerActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuzActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuzActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnDirDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirDerActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDirDerActionPerformed

    private void btnCinDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinDerActionPerformed
       if (!freno.isActivo()) {
            freno.activar();
            lblParking.setEnabled(true);
        } else {
            freno.desactivar();
            lblParking.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCinDerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCinDer;
    private javax.swing.JButton btnCinIzq;
    private javax.swing.JButton btnDirDer;
    private javax.swing.JButton btnDirIzq;
    private javax.swing.JButton btnEmer;
    private javax.swing.JButton btnLuz;
    // End of variables declaration//GEN-END:variables
}
