/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Brwni
 */
public class IFrmDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmDash
     */
    public IFrmDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOdometro = new javax.swing.JPanel();
        nvlCombustible = new javax.swing.JProgressBar();
        textCombustible = new javax.swing.JLabel();
        textKm = new javax.swing.JLabel();
        kmBackground = new javax.swing.JPanel();
        kilometraje = new javax.swing.JLabel();
        mBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelVelocimetro = new javax.swing.JPanel();
        Velocimetro = new javax.swing.JLabel();
        izquierdaOn = new javax.swing.JLabel();
        derechaOn = new javax.swing.JLabel();
        luzBaja = new javax.swing.JLabel();
        luzAlta = new javax.swing.JLabel();
        parking = new javax.swing.JLabel();
        seatbeltD = new javax.swing.JLabel();
        seatbeltP = new javax.swing.JLabel();
        wsWiperSelector = new javax.swing.JSlider();
        wWIcon = new javax.swing.JLabel();
        rpmNeedle = new javax.swing.JLabel();
        rpmGauge = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(624, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOdometro.setBackground(new java.awt.Color(204, 204, 204));
        panelOdometro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelOdometro.add(nvlCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 298, 29));

        textCombustible.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        textCombustible.setForeground(new java.awt.Color(0, 0, 0));
        textCombustible.setText("Combustible");
        panelOdometro.add(textCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        textKm.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        textKm.setForeground(new java.awt.Color(0, 0, 0));
        textKm.setText("Km recorridos");
        panelOdometro.add(textKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 20));

        kmBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kilometraje.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        kilometraje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kilometraje.setText("000000");
        kmBackground.add(kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        panelOdometro.add(kmBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 50));

        mBackground.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");

        javax.swing.GroupLayout mBackgroundLayout = new javax.swing.GroupLayout(mBackground);
        mBackground.setLayout(mBackgroundLayout);
        mBackgroundLayout.setHorizontalGroup(
            mBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
        mBackgroundLayout.setVerticalGroup(
            mBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelOdometro.add(mBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 40, 40));

        getContentPane().add(panelOdometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 310, 160));

        panelVelocimetro.setBackground(new java.awt.Color(204, 204, 204));
        panelVelocimetro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Velocimetro.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        Velocimetro.setForeground(new java.awt.Color(0, 0, 0));
        Velocimetro.setText("200km/h");
        panelVelocimetro.add(Velocimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(panelVelocimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 60));

        izquierdaOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        izquierdaOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/yellow-left-arrow.png"))); // NOI18N
        izquierdaOn.setEnabled(false);
        getContentPane().add(izquierdaOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 40, 40));

        derechaOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derechaOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/yellow-right-arrow.png"))); // NOI18N
        derechaOn.setEnabled(false);
        derechaOn.setOpaque(true);
        getContentPane().add(derechaOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 92, 40, 40));

        luzBaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luzBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/low-beam.png"))); // NOI18N
        luzBaja.setEnabled(false);
        getContentPane().add(luzBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 92, 40, 40));

        luzAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luzAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/high-beam.png"))); // NOI18N
        luzAlta.setEnabled(false);
        getContentPane().add(luzAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 92, 40, 40));

        parking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/parking brake.png"))); // NOI18N
        parking.setEnabled(false);
        getContentPane().add(parking, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 92, 40, 40));

        seatbeltD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatbeltD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatbelt.png"))); // NOI18N
        seatbeltD.setEnabled(false);
        getContentPane().add(seatbeltD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        seatbeltP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatbeltP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seatbelt.png"))); // NOI18N
        seatbeltP.setEnabled(false);
        getContentPane().add(seatbeltP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        wsWiperSelector.setMajorTickSpacing(1);
        wsWiperSelector.setMaximum(5);
        wsWiperSelector.setMinorTickSpacing(1);
        wsWiperSelector.setPaintLabels(true);
        wsWiperSelector.setPaintTicks(true);
        wsWiperSelector.setSnapToTicks(true);
        wsWiperSelector.setValue(0);
        getContentPane().add(wsWiperSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        wWIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wWIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/windshieldWiper.png"))); // NOI18N
        wWIcon.setEnabled(false);
        getContentPane().add(wWIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 40, 40));

        rpmNeedle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rpmNeedle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rpmNeedle.png"))); // NOI18N
        getContentPane().add(rpmNeedle, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 115, -1, -1));

        rpmGauge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rpmGauge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rpmGauge.png"))); // NOI18N
        getContentPane().add(rpmGauge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 250, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Velocimetro;
    private javax.swing.JLabel derechaOn;
    private javax.swing.JLabel izquierdaOn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kilometraje;
    private javax.swing.JPanel kmBackground;
    private javax.swing.JLabel luzAlta;
    private javax.swing.JLabel luzBaja;
    private javax.swing.JPanel mBackground;
    private javax.swing.JProgressBar nvlCombustible;
    private javax.swing.JPanel panelOdometro;
    private javax.swing.JPanel panelVelocimetro;
    private javax.swing.JLabel parking;
    private javax.swing.JLabel rpmGauge;
    private javax.swing.JLabel rpmNeedle;
    private javax.swing.JLabel seatbeltD;
    private javax.swing.JLabel seatbeltP;
    private javax.swing.JLabel textCombustible;
    private javax.swing.JLabel textKm;
    private javax.swing.JLabel wWIcon;
    private javax.swing.JSlider wsWiperSelector;
    // End of variables declaration//GEN-END:variables
}
